version = 1

test_patterns = [
    "tests/**"
]

exclude_patterns = [
    ".github/**"
]

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "php"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "secrets"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "shell"
