# Declaração do argumento ANTES do uso
ARG DT_ENV_ID=dummy
FROM ${DT_ENV_ID}.live.dynatrace.com/linux/oneagent-codemodules-musl:nginx-php AS dynatrace

FROM php:8.1-fpm-alpine

WORKDIR /var/www/html

COPY --from=dynatrace / /

ENV LD_PRELOAD=/opt/dynatrace/oneagent/agent/lib64/liboneagentproc.so
